apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: jhndbr/deploys:latest
        ports:
        - containerPort: 8081
        env:
        - name: hibernate_hbm2ddl_auto
          value: create
        - name: javax_persistence_jdbc_driver
          value: org.postgresql.Driver
        - name: javax_persistence_jdbc_url
          value: jdbc:postgresql://dbservice/dblibros
        - name: javax_persistence_jdbc_user
          value: postgres
        - name: javax_persistence_jdbc_password
          value: 123
