version: 2.1

orbs:
  maven: circleci/maven@1.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:17.0'
    steps:
      - checkout
      - run:
          name: Build your code
          command: mvn clean install

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
