version: 2.1

orbs:
  maven: circleci/maven@1.1
  docker: circleci/docker@1.5.0

executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'

jobs:
  publishLatestToHub:
    executor: docker/default  # Usar un executor existente, como el predeterminado "docker/default".
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME"


